"""remove duracion_min from servicios

Revision ID: e9e6824997c0
Revises: b4f4858b4a25
Create Date: 2026-07-20 12:56:42.603495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9e6824997c0'
down_revision: Union[str, Sequence[str], None] = 'b4f4858b4a25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servicios', 'duracion_min')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema: vuelve a crear la columna duracion_min."""
    # El server_default rellena las filas existentes para no violar NOT NULL;
    # luego se quita (la columna original no tenía default).
    op.add_column(
        "servicios",
        sa.Column("duracion_min", sa.Integer(), nullable=False, server_default="30"),
    )
    op.alter_column("servicios", "duracion_min", server_default=None)
